const OPERATION_STATUSES = {
    FAILED: 'FAILED',
    'NOT-STARTED': 'NOT-STARTED',
    'IN-PROGRESS': 'IN-PROGRESS',
    COMPLETED: 'COMPLETED',
    'NOT-READY': 'NOT-READY'
};

module.exports = { OPERATION_STATUSES };
